services:
  - type: web
    name: moviesfreak
    runtime: node
    plan: free
    rootDir: .
    buildCommand: cd frontend && npm install --include=dev && npm run build && cp -r dist ../backend/client && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: VITE_TMDB_READ_ACCESS_TOKEN
        sync: false
      - key: VITE_API_BASE_URL
        value: ""
      - key: VITE_TMDB_BASE_URL
        value: https://api.themoviedb.org/3
      - key: VITE_TMDB_IMAGE_BASE
        value: https://image.tmdb.org/t/p/w500

